classdef Feature
    
    % Enumeration of features that can be extracted for Oink class
    
    enumeration
        scgPEP, scgLVET, truePEP, trueLVET, scgPAT, scgPTT, truePAT, truePTT, ...
            hr, hrvDifference, hrvSpectral, hrvPoincare, scgAmplitudeApex, ...
            scgAmplitudeSternum, ppgAmplitudeProximal, ppgAmplitudeDistal, ...
            scgPEPOverLVET, truePEPOverLVET, proximalSPO2, distalSPO2, scgSQI, ...
            ppgSQI, meanAorticPressure, meanFemoralPressure, meanWedgePressure, ...
            meanRAPressure, aorticPressureSQI, femoralPressureSQI, systolicPressure, ...
            diastolicPressure, pulsePressure, scgPATCalibrated, scgPTTCalibrated, ...
            truePATCalibrated, truePTTCalibrated, hrvSpectralLF, hrvSpectralHF, ...
            hrvPoincareEig1, hrvPoincareEig2, ppgIHAT, trueIHAT, femoralPPGPPV, ...
            femoralPressurePPV, all
    end
end

